<a href="https://colab.research.google.com/github/pingao2019/DS-Unit-4-Sprint-2-Neural-Networks/blob/master/LS_DS_421_Intro_to_NN_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:initial data for the neural network.

### Hidden Layer:— intermediate layer between input and output layer and place where all the computation is done.

### Output Layer:— produce the result for given inputs

### Neuron: a neuron is a mathematical function that model the functioning.  Typically, a neuron compute the weighted average of its input, and this sum is passed through a nonlinear function, often called activation function, such as the sigmoid.

### Weight:

### Activation Function:Typically, a neuron compute the weighted average of its input, and this sum is passed through a nonlinear function, often called activation function, such as the sigmoid.

### Node Map:A node, also called a neuron or Perceptron, is a computational unit that has one or more weighted input connections, a transfer function that combines the inputs in some way, and an output connection. Nodes are then organized into layers to comprise a network. A Hopfield network (HN) is a network where every neuron is connected to every other neuron; it is a completely entangled plate of spaghetti as even all the nodes function as everything. Each node is input before training, then hidden during training and output afterwards

### Perceptron:
The first and simplest kind of neural network that we could talk about is the perceptron. A perceptron is just a single node or neuron of a neural network with nothing else. It can take any number of inputs and spit out an output. 

## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### My Answer:
 Input Layer has the initial data for the neural network.# Hidden Layer-intermediate layer between input and output layer and place where all the computation is done. Output Layer produce the result for given inputs. : a neuron is a mathematical function that model the functioning.  Typically, a neuron compute the weighted average of its input, and this sum is passed through a nonlinear function, often called activation function, such as the sigmoid.A node, also called a neuron or Perceptron, is a computational unit that has one or more weighted input connections, a transfer function that combines the inputs in some way, and an output connection. Nodes are then organized into layers to comprise a network. Sometimes every neuron is connected to every other neuron; it is a completely entangled plate of spaghetti as even all the nodes function as everything. Each node is input before training, then hidden during training and output afterwards. The first and simplest kind of neural network that we could talk about is the perceptron. A perceptron is just a single node or neuron of a neural network with nothing else. It can take any number of inputs and spit out an output. 

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

Establish training data

In [0]:
import numpy as np
import pandas as pd
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [0]:
df

x1  x2  y
0   0   0  1
1   1   0  1
2   0   1  1
3   1   1  0

In [0]:
inputs = np.array([
                  [0,0],
                  [1,1],
                  [1,0],
                  [0,1]                   

])

correct_outputs = [[1], [1], [1], [0]]

Sigmoid activation function and its derivative for updating weights

In [0]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)

Initialize random weights for our three inputs

In [0]:
weights = np.random.random((2,1))

In [0]:
weights

array([[0.28825648],
       [0.8356776 ]])

Calculate weighted sum of inputs and weights

In [0]:
weighted_sum = np.dot(inputs, weights)
weighted_sum

array([[0.        ],
       [1.12393408],
       [0.28825648],
       [0.8356776 ]])

Output the activated value for the end of 1 training epoch 

In [0]:
activated_output = sigmoid(weighted_sum)
activated_output

array([[0.5       ],
       [0.75471772],
       [0.57156924],
       [0.69755409]])

take difference of output and true values to calculate error

In [0]:
error = correct_outputs - activated_output
error

array([[ 0.5       ],
       [ 0.24528228],
       [ 0.42843076],
       [-0.69755409]])

Gradient descent/backprop - magic!

In [0]:
adjustments = error * sigmoid_derivative(weighted_sum)

In [0]:
weights += np.dot(inputs.T, adjustments)
weights

array([[0.43857607],
       [0.73391933]])

Put it all together

In [0]:
# Steps we've already done: 
# 1. Randomly Initialized Weights already. Those are in memory as `weights`
# 2. We've already got input data & correct_outputs


# Update our weights 10,000 times - (fingers crossed that this process reduces error)
for iteration in range(1000):
    
    # Weighted sum of inputs / weights
    weighted_sum = np.dot(inputs, weights)
    
    # Activate!
    activated_output = sigmoid(weighted_sum)
    
    # Cac error
    error = correct_outputs - activated_output
    
    adjustments = error * sigmoid_derivative(weighted_sum)
    
    # Update the Weights
    weights += np.dot(inputs.T, adjustments)
    
print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)

Weights after training
[[ 6.49612278]
 [-3.13983072]]
Output after training
[[0.5       ]
 [0.96629249]
 [0.99849134]
 [0.0415159 ]]


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [0]:
import numpy as np
import pandas as pd

In [0]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [0]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

features = list(diabetes)[:-1]
target = list(diabetes)[-1:]
# Instantiate normalizer
normalizer = Normalizer()

# Normalize the feature data
X = normalizer.fit_transform(diabetes[features])
# Set target vector
y = diabetes[target]


In [0]:
X

array([[0.03355237, 0.82762513, 0.40262844, ..., 0.18789327, 0.00350622,
        0.27960308],
       [0.008424  , 0.71604034, 0.55598426, ..., 0.22407851, 0.00295683,
        0.26114412],
       [0.04039768, 0.92409698, 0.32318146, ..., 0.11765825, 0.00339341,
        0.16159073],
       ...,
       [0.02691539, 0.65135243, 0.38758161, ..., 0.14103664, 0.00131885,
        0.16149234],
       [0.00665306, 0.83828547, 0.39918356, ..., 0.20025708, 0.00232192,
        0.31269379],
       [0.00791454, 0.73605211, 0.55401772, ..., 0.24060198, 0.00249308,
        0.18203439]])

In [0]:
y.head()

Outcome
0        1
1        0
2        1
3        0
4        1

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [0]:
class Perceptron:
    
    def __init__(self, niter = 10):
        self.niter = niter
    
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def sigmoid_derivative(self, x):
        sx = sigmoid(x)
        return sx * (1-sx)

    def fit(self, X, y):
        """Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """
        # Randomly Initialize Weights
        self.weight = 2 * np.random.random((8,1)) - 1

        for i in range(self.niter):
            # Weighted sum of inputs / weights
            weighted_sum = np.dot(X, self.weight) + 1
            # Activate!
            activated_output = self.sigmoid(weighted_sum)
            # Cac error
            error = y - activated_output
            adjustments = error * self.sigmoid_derivative(weighted_sum)
            # Update the Weights
            self.weight = self.weight + np.dot(X.T, adjustments)

        return self
    
    
    def predict(self, X):
        """Return class label after unit step"""
        weighted_sum = np.dot(X, self.weight) + 1
        activated_output = self.__sigmoid(weighted_sum)
        return np.round(activated_output)

In [0]:
model = Perceptron()
model.fit(X, y)
model.predict(X)

In [0]:
from sklearn.linear_model import LogisticRegressionCV

lr = LogisticRegressionCV(cv=5, multi_class='multinomial')
lr.fit(X_train, y_train)
lr.score(X_test,y_test) # Basically a random guess

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.640625

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?